### ISSUE TITLE
Issue Tracker

### ISSUE THREAD

**Issue by mudroock** [mudroock/Gesior-AAC#15]
- [ ] Adicionar bind na pagina houses.
- [ ] Corrigir ajax que informa disponibilidade de nome de character.
- [ ] Corrigir webshop para compra de produtos.
- [ ] Adicionar metodos de pagamento (Deposito, Paypal, Picpay)
